### ISSUE TITLE
Remote XUL Manager not saving the domains

### ISSUE THREAD

**Issue by rajneesh75** [jvillalobos/Remote-XUL-Manager#20]
Hello

I have been trying to add domains to Remote XUL Manager. I do it and it works. But when I close firefox and restart it, the domain names saved earlier are gone.

This issue has recently started. It was not earlier. I also tried reinstalling Firefox/Remote XUL Manager from scratch but didn't work. My firefox version is 50.1.0.

Any advice. Thanks

**Comment by jvillalobos** [comment]
It sounds like something is happening to the `permissions.sqlite` file in your profile folder. I suggest you [locate your profile folder](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data), and see if the file size changes when (1) you add new domains to the list, (2) close Firefox, (3) start it again.

**Comment by rajneesh75** [comment]
The file size doesn't change and neither does the file timestamp when I add new domains. Also when I add new domains in the Remote XUL Manager window and close it and then reopen it, the domains are there. Its only when I close Firefox and restart it that the domains are gone.

**Comment by rajneesh75** [comment]
The file size doesn't change when I add new domains. Also when I add new domains in the Remote XUL Manager window and close it and then reopen it, the domains are there. Its only when I close Firefox and restart it that the domains are gone.

**Comment by jvillalobos** [comment]
And you can load remote XUL pages in the domains right after you add them to the list?

**Comment by rajneesh75** [comment]
Yes.

**Comment by jvillalobos** [comment]
It sounds like the file is being written to, which is something that Firefox should handle. Maybe your browser is crashing instead of quitting correctly, and that prevents the file from being updated. At any rate, it's definitely outside of what the add-on does, so there's nothing I can do here.
