### ISSUE TITLE
Whitelist all the url of local directory at once?

### ISSUE THREAD

**Issue by arshdkhn1** [jvillalobos/Remote-XUL-Manager#23]
Hi, I want to whitelist all the urls of a directory at once but somehow what I am doing is not working. I have a local file url like - `file:///abc/def/xuls/a\box.xul`. I want to white list all the files in `file:///abc/def/xuls/`, what should I do?

**Comment by jvillalobos** [comment]
You need to enter `<file>` in the whitelist. This should whitelist all local `file://` URLs. It's not possible to whitelist only certain local directories.

**Comment by arshdkhn1** [comment]
Ohk, thanks. I found another way to whitelist all local files by making a `dom.allow_XUL_XBL_for_file` whose value is true in `about:config`.

**Comment by jvillalobos** [comment]
Yeah, that's what the extension does behind the scenes ;)

**Comment by arshdkhn1** [comment]
I am having some problems when attaching images or xbl file.. Can you tell me what might be the problem?

**Comment by jvillalobos** [comment]
I wouldn't know for sure. Keep in mind that running XUL this way has not been officially supported for years and will break more and more with time.
